version: '3'

services:
  mysql:
    image: mysql:5.7.16
    hostname: mysqlhost
    container_name: mysql83
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
      - ./db/mysql:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld

    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_ROOT_HOST=%
      - TZ='Asia/Shanghai'
      - LANG=C.UTF-8

      #    ports:
      #- '3306:3306'
