version: '3.8'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
